version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: study
        MYSQL_USER: user
        MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
