CREATE TABLE user (
  created_at DATETIME
);

INSERT INTO user (created_at)
SELECT DATE_SUB(FROM_UNIXTIME(0), INTERVAL FLOOR(RAND() * 1576800000) SECOND)
FROM (
    SELECT 1 UNION ALL
    SELECT 2 UNION ALL
    SELECT 3 UNION ALL
    SELECT 4 UNION ALL
    SELECT 5 UNION ALL
    SELECT 6 UNION ALL
    SELECT 7 UNION ALL
    SELECT 8 UNION ALL
    SELECT 9 UNION ALL
    SELECT 10
) AS t
LIMIT 100;